# Generated by Django 5.0.6 on 2024-05-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebritypicker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ahow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('actors', models.ManyToManyField(related_name='shows', to='celebritypicker_app.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Aovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('actors', models.ManyToManyField(related_name='movies', to='celebritypicker_app.actor')),
            ],
        ),
        migrations.CreateModel(
            name='UserActiviy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movie', models.CharField(max_length=50)),
                ('show', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.RemoveField(
            model_name='show',
            name='actors',
        ),
        migrations.DeleteModel(
            name='movie',
        ),
        migrations.DeleteModel(
            name='show',
        ),
    ]
