# Generated by Django 5.0.6 on 2024-05-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebritypicker_app', '0002_ahow_aovie_useractiviy_remove_movie_actors_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aovie',
            new_name='Movie',
        ),
        migrations.RenameModel(
            old_name='Ahow',
            new_name='Show',
        ),
    ]
