# Generated by Django 5.0.6 on 2024-05-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebritypicker_app', '0010_remove_randompick_movie_randompick_overview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorites',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorites_movies',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='celebritypicker_app.movie'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorites_shows',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='celebritypicker_app.show'),
        ),
    ]
