# Generated by Django 5.0.6 on 2024-05-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebritypicker_app', '0011_remove_userprofile_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorites_movies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorites_shows',
        ),
        migrations.AddField(
            model_name='randompick',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='celebritypicker_app.movie'),
        ),
    ]
